### ISSUE TITLE
DFT Cartesian coordinates conversion into Log-polar coordinates in java using openCV

### ISSUE THREAD

**Issue by tehseenmayar** [sthoduka/imreg_fmt#1]
hello.i am working on a project in java using openCV and i have calculated the DFT in Cartesian coordinates of an image and now i want to convert that into Log-polar coordinates. i have attached the DFT magnitude image that i have calculated in DFT and now i want to convert that into Log-polar coordinates. Any type of help would be appreciated.
![magnitude](https://user-images.githubusercontent.com/29973339/30514586-da2da46c-9acc-11e7-88d5-1fb639876988.png)

**Comment by sthoduka** [comment]
Hey @tehseenmayar , sorry for the late reply.
I haven't used OpenCV in Java, but there seems to be a logPolar function you can use: http://docs.opencv.org/java/3.1.0/org/opencv/imgproc/Imgproc.html#logPolar-org.opencv.core.Mat-org.opencv.core.Mat-org.opencv.core.Point-double-int-

In this project, I used a fixed map between Cartesian and Log-Polar coordinates and then used cv::remap to remap the pixels in a given image to log-polar coordinates. You can find that in the `createLogPolarMap` and `remapLogPolar` functions here: https://github.com/sthoduka/imreg_fmt/blob/master/src/image_transforms.cpp 
You can try porting that to Java, or just use the built-in function from opencv.

**Comment by tehseenmayar** [comment]
thanks for the reply but i have solved that issue
but now i have another issue  because i am new to opencv and i hope you will help me
i want to write a mat object into xml file in java using opencv class "FileStorage" but i am stuck .. the code so far i have written is this

this is my java code
 opencv_core.FileStorage mfs= new opencv_core.FileStorage(String.valueOf(mymagnitude), opencv_core.FileStorage.WRITE);
                mfs.open("test.xml", opencv_core.FileStorage.WRITE);
                mfs.release();
"mymagnitude" is the mat object which i am trying to write to a file

**Comment by sthoduka** [comment]
again, I haven't used openCV in Java, so I'm not sure if this is correct. It seems like you should do the following:

```
// create a FileStorage object with the file name in write mode
opencv_core.FileStorage mfs= new opencv_core.FileStorage("test.xml", opencv_core.FileStorage.WRITE);
// write the Mat to file
mfs.write("magnitude", mymagnitude);
// close the file
mfs.release()
```



Please read through the documentation:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.FileStorage.html

In particular look at what the constructor is expecting (in this case, just the file name and the WRITE flag), and the `write` function which can take a variable name and the Mat that you want to save.

**Comment by tehseenmayar** [comment]
thanks sir!
this is what i just did..
can you tell me how to read the xml file back and store the data into mat
object?

**Comment by sthoduka** [comment]
Please ask the question on stackoverflow.com or some other such forum because I don't know enough to help you.. Sorry
