### ISSUE TITLE
How to use OpenCV warpPolar

### ISSUE THREAD

**Issue by mostafafarzaneh** [sthoduka/imreg_fmt#10]
I would like to know why you have not used OpenCV `warpPolar` method and implemented it by yourself.
I am trying to understand why I cannot use the OpenCV `warpPolar` instead.

**Comment by sthoduka** [comment]
I think it should be possible to use the `warpPolar` function from OpenCV as well. I can't remember if I tried it. I wanted to keep as close to the implementation in [imreg_dft](https://github.com/matejak/imreg_dft) as possible, which is why I did not use OpenCV's function.

**Comment by mostafafarzaneh** [comment]
Thanks,
I used the OpenCV `warpPolar` as follows:
```
double maxRadius = (im_dft_cv.rows * 1.1)/2.0; //I got this line from your code. Do not know why this works.
int flags = cv::INTER_CUBIC + cv::WARP_FILL_OUTLIERS;
warpPolar(im_dft_cv, log_polar_cv, im_dft_cv.size(), center, maxRadius, flags+cv::WARP_POLAR_LOG);
```

Also, I noticed that I need to make the results of `phaseCorrelation`, negative. After that, I replaced [this](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_transforms.cpp#L62) line with the following:
```
rotation = rotation * 2;
```

I am not good at math. So I cannot explain what is the difference between OpenCV and your implementation of polar.

I attached two images. 1-polar: your implementation 2- polar_cv: OpenCV log-polar.

Your implementation:
![polar](https://user-images.githubusercontent.com/77715693/188846911-d1028360-d052-46f8-b444-3b9c2059025d.jpg)

OpenCV implimentation:
![polar_cv](https://user-images.githubusercontent.com/77715693/188846930-37b2c5eb-382b-464f-ac73-1e3781ad38be.jpg)

**Comment by mostafafarzaneh** [comment]
I realized that I passed the whole FFT image to `warpPolar`. The original paper mentioned:

> Only the upper two quadrants of the Fourier log-magnitude spectra of images are used to map them to polar plane. This is because of the fact that the Fourier spectrrum is conjugate symmetric for real sequences

 This will fix the problem where I need to multiply rotation.

**Comment by sthoduka** [comment]
Sounds good. I'll have to look into it in more detail when I get the time. The reason for using `1.1` also originates from the [imreg_dft](https://github.com/matejak/imreg_dft/blob/master/src/imreg_dft/imreg.py#L600) version.
