### ISSUE TITLE
Can it be accelerated?

### ISSUE THREAD

**Issue by zhenhuamo** [sthoduka/imreg_fmt#14]
Can the running speed be further optimized? Running efficiency is too slow

**Comment by sthoduka** [comment]
How long does it take, and what is the size of the image? Are you setting the build type to Release?

**Comment by zhenhuamo** [comment]
Release mode  658*641 image 500ms.

**Comment by sthoduka** [comment]
Thanks for the info. Unfortunately, I'm not sure how to speed it up beyond that.

**Comment by sthoduka** [comment]
one small improvement might be to use separate threads to perform FFT on the two images [here](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L111). This would mean initializing two `forward_plan_` objects.

**Comment by sthoduka** [comment]
you might see a slight improvement by adding the following flags [here](https://github.com/sthoduka/imreg_fmt/blob/master/CMakeLists.txt#L32)

`target_compile_options(imreg_fmt PUBLIC -mavx2 -mfma)`

**Comment by zhenhuamo** [comment]
Thank you very much for your help, but I found a problem. When I differentiate the matched image with the reference image, sometimes it does not match.

**Comment by sthoduka** [comment]
There's another issue (#13) where we were discussing a similar problem. The program does not find the correct transformation for certain image sizes. I'm not yet sure why. Have you tried with the [Python tool](https://github.com/matejak/imreg_dft) if you get the correct results?

**Comment by sthoduka** [comment]
the code has been updated to use the phaseCorrelate function from OpenCV, with which you should see some speed up. See https://github.com/sthoduka/imreg_fmt/issues/15
