### ISSUE TITLE
Failed to make

### ISSUE THREAD

**Issue by phenix1983** [sthoduka/imreg_fmt#2]
cmake -DCMAKE_BUILD_TYPE=Release ..

**Comment by phenix1983** [comment]
just installed fftw3, resolved.

**Comment by wafisher** [comment]
I had to use this on Mac OS X:

```
-DCMAKE_CXX_FLAGS='-isystem /usr/local/include'
```

I then ran into a handful of issues (about 5) around constants, probably because I had the wrong version of OpenCV but manually fixing them one by one did the trick.

**Comment by sthoduka** [comment]
@wafisher thanks! I added this to the README.

What were the other issues you had?

**Comment by wafisher** [comment]
I changed `CV_LOAD_IMAGE_COLOR` to `cv::IMREAD_COLOR`, `CV_BGR2GRAY` to `cv::COLOR_BGRA2GRAY` and `CV_INTER_CUBIC` to `cv::INTER_CUBIC`. 

I have OpenCV 4.3.0.
