### ISSUE TITLE
How to plot translation peak?

### ISSUE THREAD

**Issue by andreavolk12** [sthoduka/imreg_fmt#3]
Hi,
thanks for the great code and explanation it was really helpful for me.
I have a question about plotting the translation peak in phase correlation.
I don't have an idea how to get this picture(in link), does anyone have some advice?

![image](https://user-images.githubusercontent.com/54620360/63892695-84da3780-c9e8-11e9-840d-835879e51274.png)

**Comment by sthoduka** [comment]
Hi,
I plotted that using matplotlib; it was a long time ago, so I don't remember how I exported the data.

Anyway, you need to plot the values of MatrixXd called `abs` [here](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L141). You could save the matrix to a file, and plot it using matplotlib. 
If I get some time later, I can write a script for that.

**Comment by andreavolk12** [comment]
Thanks a lot for the answer. 
If you have some time later, that would be great, because I'm stuck with this. 
(I try to do that in Python)

**Comment by sthoduka** [comment]
hey, I've pushed to the `sample-plotter` branch. On that branch, run `image_main` with the '-s' option as follows:

`./image_main ../images/horse1.png ../images/horse2.png -s` 
This will write two files `trans_cps.txt` and `rot_scale_cps.txt`. You can now pass these files to the plotter (`python scripts/plotter.py trans_cps.txt`) and it will plot the surface plot.

For the example you have above, use the images `horse3.png` and `horse4.png` and plot `rot_scale_cps.txt`.

**Comment by andreavolk12** [comment]
Thank you very much.
