### ISSUE TITLE
how to get peak of IFFT of phase diff

### ISSUE THREAD

**Issue by Sunyouteng** [sthoduka/imreg_fmt#4]
In paper the peak should greater than 0.03. 
So i want to know how to get it, it should be an interface.

**Comment by sthoduka** [comment]
Hi, 
the peak is calculated here: https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L144
The variables `row` and `col` passed to the function will contain the location of the peak when the function returns.

An example of the function being called is here: https://github.com/sthoduka/imreg_fmt/blob/master/src/image_registration.cpp#L43
