### ISSUE TITLE
How to fix the scale?

### ISSUE THREAD

**Issue by ONMEKEEP** [sthoduka/imreg_fmt#8]
Hi @sthoduka 

There is no scale transformation in my image data. I want to fix the scale. How can I do this?

**Comment by sthoduka** [comment]
What do you mean by there is no scale transformation?

**Comment by ONMEKEEP** [comment]
> What do you mean by there is no scale transformation?

There is no scaling between the two images. That is, the output of scale is 1.
![image](https://user-images.githubusercontent.com/37762029/149908267-57c3e556-2390-4ac9-8cc3-80e618cd204f.png)

**Comment by sthoduka** [comment]
Is that the output for your two images? I see a scale of `1.22` there; do you mean that your images should not have a scale difference?

**Comment by ONMEKEEP** [comment]
> Is that the output for your two images? I see a scale of `1.22` there; do you mean that your images should not have a scale difference?

Yes. And I found that imreg_dft provides a fixed scale option.
![image](https://user-images.githubusercontent.com/37762029/149917447-137c29bd-f8a2-4f86-a520-0c72b043ee56.png)
So I wonder if imreg_fmt can also be achieved.

**Comment by sthoduka** [comment]
the scaling and rotation are performed [here](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_registration.cpp#L33), so if you don't want to apply any scaling, just set `scale = 1.0;` before that line.

**Comment by ONMEKEEP** [comment]
> the scaling and rotation are performed [here](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_registration.cpp#L33), so if you don't want to apply any scaling, just set `scale = 1.0;` before that line.

OK. Thank you very much. I will try later.
