### ISSUE TITLE
How to calculate a number for similarity

### ISSUE THREAD

**Issue by mostafafarzaneh** [sthoduka/imreg_fmt#9]
Hey. Thanks for the effort on this. It saved me lots of time.

I need a number to tell me how much the images are similar. For example, OpenCV [`phaseCorrelate`](https://docs.opencv.org/3.4/d7/df3/group__imgproc__motion.html#ga552420a2ace9ef3fb053cd630fdb4952) returns a double(`response`) that can be used as a similarity indication.
I was thinking of using [this](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L165) similar to `phaseCorrelation` response, but I cannot figure out the right way to use it.
From OpenCV doc:
> the response parameter is computed as the sum of the elements of r within the 5x5 centroid around the peak location. It is normalized to a maximum of 1 (meaning there is a single peak) and will be smaller when there are multiple peaks.

>response: Signal power within the 5x5 centroid around the peak, between 0 and 1 (optional).

**Comment by sthoduka** [comment]
hey @mostafafarzaneh
it does look like openCV computes `response` as the sum of a defined neighbourhood divided by the size of the image.
See [here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L498) and [here](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L592). `M*N` doesn't seem to be the exact image size though, but rather the value computed using [getOptimalDFTSize](https://github.com/opencv/opencv/blob/e16cb8b4a23fc1b6b7b99155a0d33f523262db76/modules/core/include/opencv2/core.hpp#L2325). They mention in one of the comments that the maximum size of the peak is roughly equal to `M*N`. I'm not sure why that is, but I assume there's a mathematical explanation for that, and can be tested.

**Comment by mostafafarzaneh** [comment]
Thanks.

I should mention that I use an image of size 512*512. So`getOptimalDFTSize` wont change the dimension.

At first, I divided the sum at `getCenterOfMass` by M*N([here (https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L165)). But I got a number above 1.

Then I used the OpenCV [`weightedCentroid`](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L436) function and pass it the exact parameter as passed to `getCenterOfMass`. It returned the exact results as `getCentreOfMass`.

But if I use OpenCV `phaseCorrelation` method, the returned `col` and `row` are similar(not the same) as your `phaseCorrelation` method and the `response` is under 1 which is correct.

I think there is a difference between OpenCV and FFTW in how they calculate DFT. Because in the OpenCV phaseCorrelate the minimum number in the matrix after calculating FFT stuff([the C Mat](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L581)), is a 3 digit negative but the same matrix in your implementation[(abs)](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L142) has a minimum of a tiny positive number. The maximum number is the same though. But I can be wrong.

**Comment by sthoduka** [comment]
One difference seems to be that here we are taking the [absolute value](https://github.com/sthoduka/imreg_fmt/blob/master/src/image_dft.cpp#L141) of the cross power spectrum. Unless I missed it, it doesn't seem like the openCV version does that. That would explain the negative numbers from OpenCV and tiny positive number here. That shouldn't affect the location of the peak I guess, but would affect your similarity score.
